// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohphgvzaxvmtjyaiqdaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ocGhndnpheHZtdGp5YWlxZGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTczOTAsImV4cCI6MjA1ODI3MzM5MH0.CfSFs5zSvn0EvjMhtSOq4dFsEZKtiQjAFK7GsiEA4hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);